config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users

  resources :users, only: :index
  resources :personal_messages, only: %i[new create]
  resources :conversations, only: %i[index show]

  resource :profile, only: %i[edit update]
  controller :page do
    %w[home dashboard].each { |page| get page }
  end

  namespace :admin do
    resources :users, except: :show

    root '/admin/users#index'
  end

  root 'page#home'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :receiver, class_name: 'User'
  has_many :personal_messages, -> { order(created_at: :asc) }, dependent: :destroy

  validates :author, uniqueness: { scope: :receiver }

  def self.participating(user)
    where("(conversations.author_id = ? OR conversations.receiver_id = ?)", user.id, user.id)
  end

  def self.between(sender_id, receiver_id)
    where(author_id: sender_id, receiver_id: receiver_id).or(where(author_id: receiver_id, receiver_id: sender_id)).limit(1)
  end

  def with(current_user)
    author == current_user ? receiver : author
  end

  def participates?(current_user)
    author == current_user || receiver == current_user
  end
end

app/models/personal_message.rb
class PersonalMessage < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates :body, presence: true 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :authors, class_name: 'Conversation', foreign_key: 'author_id'
  has_many :receivers, class_name: 'Conversation', foreign_key: 'receiver_id'
  has_many :personal_messages, dependent: :destroy

  def self.available_to_message(current_user_id)
    where(blocked: false).where.not(id: current_user_id)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :set_user, only: %i[edit update destroy]

  def index
    @users = User.all
  end

  def edit
  end

  def new
    @user = User.new
  end

  def update
    user_attributes = params[:user][:password].blank? ? user_params.except(:password, :password_confirmation) : user_params
    if @user.update(user_attributes)
      redirect_to admin_users_path, notice: 'User was updated'
    else
      render :edit
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: 'User was created'
    else
      render :new
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :blocked)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def after_sign_in_path_for(resource)
    if current_admin
      admin_root_path
    else
      dashboard_path
    end
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_conversation, except: [:index]
  before_action :check_participating!, except: [:index]

  def index
    @conversations = Conversation.participating(current_user).order('updated_at DESC')
  end

  def show
    @conversation = Conversation.find_by(id: params[:id])
    update_message_to_read(@conversation)
    @personal_message = PersonalMessage.new
  end

  private

  def set_conversation
    @conversation = Conversation.find_by(id: params[:id])
  end

  def update_message_to_read(conversation)
    messages = conversation.personal_messages

    if !messages.empty? && (messages.last.user != current_user)
      messages.update_all(read: true)
    end
  end

  def check_participating!
    redirect_to root_path unless @conversation && @conversation.participates?(current_user)
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  before_action :authenticate_user!, only: :dashboard

  def home
  end

  def dashboard
    unread_messages_info = UnreadMessagesService.new(current_user).count_messages
    @messages_count = unread_messages_info[:count]
    @users = User.find(unread_messages_info[:receiver_ids])
  end
end

app/controllers/personal_messages_controller.rb
class PersonalMessagesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_conversation!

  def new
    redirect_to conversation_path(@conversation) and return if @conversation
    @personal_message = current_user.personal_messages.build
  end

  def create
    @conversation ||= Conversation.create(author_id: current_user.id,
                                          receiver_id: @receiver.id)
    @personal_message = current_user.personal_messages.build(personal_message_params)
    @personal_message.conversation_id = @conversation.id
    @personal_message.save!

    flash[:success] = "Your message was sent!"
    redirect_to conversation_path(@conversation)
  end

  private

  def personal_message_params
    params.require(:personal_message).permit(:body)
  end

  def find_conversation!
    if params[:receiver_id]
      @receiver = User.find(params[:receiver_id])
      redirect_to(root_path) and return unless @receiver
      @conversation = Conversation.between(current_user.id, @receiver.id).first
    else
      @conversation = Conversation.find(params[:conversation_id])
      redirect_to(root_path) and return unless @conversation && @conversation.participates?(current_user)
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user

  def edit
  end

  def update
    user_attributes = params[:user][:password].blank? ? user_params.except(:password, :password_confirmation) : user_params

    if @user.update(user_attributes)
      redirect_to edit_profile_path, notice: 'You account was updated'
    else
      render :edit
    end
  end

  private

  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.available_to_message(current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/users/_form.slim
= form_for([:admin, @user]) do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message
  
  p
    label Email
    = f.email_field :email

  p
    label Password
    = f.password_field :password

  p
    label Password confirmation
    = f.password_field :password_confirmation

  p
    label Blocked?
    = f.check_box :blocked

  p = f.submit

app/views/admin/users/edit.html.slim
h1 Edit user with ID: #{@user.id}

= render 'form'

app/views/admin/users/index.html.slim
table
  thead
    tr
      th user id
      th email
      th

  tbody
    tr: td colspan='3' = link_to 'Add New User', new_admin_user_path
    - @users.each do |u|
      tr
        td = u.id
        td = u.email
        td
          = link_to 'Edit', edit_admin_user_path(u)
          = link_to 'Destroy', admin_user_path(u), method: :delete, data: { confirm: 'Are you sure?' }

app/views/admin/users/new.slim
h1 Add new user
= render 'form'

app/views/conversations/_conversations.slim
div
  |Chatting with #{conversation.with(current_user).email}
  br
  em = conversation.personal_messages.last.body.truncate(50)
  br
  = link_to 'View conversation', conversation_path(conversation)
  hr

app/views/conversations/_personal_messages.slim
p = personal_message.body
p 
  |at
  strong = personal_message.created_at
  br
  |by 
  strong = personal_message.user.email
hr

app/views/conversations/index.html.slim
h1 Your conversations

#conversations
  = render @conversations

app/views/conversations/show.slim
h1 Chatting with #{@conversation.with(current_user).email}

#conversation-main
  #conversation-body
    = render @conversation.personal_messages

  = form_for @personal_message do |f|
    = hidden_field_tag 'conversation_id', @conversation.id
    = f.label :body
    = f.text_area :body

    = f.submit

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tickets</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%- if current_user.present? %>
      <%= render 'shared/navbar'%>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/page/_user.slim
li 
  = user.email
  | | 
  = link_to 'show a message', new_personal_message_path(receiver_id: user)

app/views/page/dashboard.slim
h1 you have #{@messages_count} unread messages

= link_to 'Check new message', dashboard_path

ul
  - @users.each do |user|
    == render 'page/user', user: user

app/views/page/home.html.slim
h1 GO LOGIN

= link_to 'Admin', new_admin_session_path
br
= link_to 'User', new_user_session_path

app/views/personal_messages/_personal_message.slim
= personal_message.body
p
  |at 
  strong = personal_message.created_at
  br
  |by <
  strong = personal_message.user.email
hr

app/views/personal_messages/new.slim
h1 New message to #{@receiver.email}

= form_for @personal_message do |f|
  = hidden_field_tag 'receiver_id', @receiver.id

  = f.label :body
  = f.text_area :body

  = f.submit

app/views/profiles/edit.html.slim
p#notice = notice

= form_for(@user, url: profile_path, method: :PUT) do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  p
    label Email: 
    = f.email_field :email

  p
    label Password:
    = f.password_field :password

  p
    label Password Confirmation
    = f.password_field :password_confirmation

  p = f.submit

app/views/shared/_navbar.slim
.navbar
  = link_to 'Home', dashboard_path
  = link_to 'Users', users_path
  = link_to 'Profile', edit_profile_path

app/views/users/_user.slim
li 
  = user.email
  | | 
  = link_to 'send a message', new_personal_message_path(receiver_id: user)

app/views/users/index.slim
h1 Users

ul = render @users